@extends('layouts.admin')
@section('title','Dashboard') @section('page','Dashboard')
@section('content')
<div class="admin-page-heading"><div><span class="admin-kicker">EDITORIAL OVERVIEW</span><h1>Good {{ now()->hour < 12 ? 'morning' : (now()->hour < 18 ? 'afternoon' : 'evening') }}, {{ auth('admin')->user()->name }}</h1><p>Here is what is happening across your magazine.</p></div><a href="{{ route('admin.articles.create') }}" class="btn btn-danger"><i class="bi bi-plus-lg me-2"></i>Write a story</a></div>
<div class="row g-3 admin-stat-row">
    @foreach([['Stories', $articleCount, 'bi-file-earmark-text', 'All editorial content'],['Published', $publishedCount, 'bi-send-check', 'Live on the website'],['Categories', $categoryCount, 'bi-collection', 'Editorial sections'],['Subscribers', $subscriberCount, 'bi-envelope-paper', 'Newsletter readers']] as [$label,$value,$icon,$hint])
    <div class="col-sm-6 col-xl-3"><div class="admin-stat"><div class="admin-stat-icon"><i class="bi {{ $icon }}"></i></div><span>{{ $label }}</span><strong>{{ number_format($value) }}</strong><small>{{ $hint }}</small></div></div>
    @endforeach
</div>
<div class="admin-panel mt-4"><div class="admin-panel-head"><div><h2>All stories</h2><p>Manage, edit and publish your content.</p></div></div>
<form class="admin-filter-bar" method="GET" action="{{ route('admin.dashboard') }}"><div class="input-group"><span class="input-group-text"><i class="bi bi-search"></i></span><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Search stories"></div><select class="form-select" name="status"><option value="">All statuses</option><option value="published" @selected(request('status')==='published')>Published</option><option value="draft" @selected(request('status')==='draft')>Drafts</option></select><select class="form-select" name="category_id"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('category_id')==$category->id)>{{ $category->name }}</option>@endforeach</select><button class="btn btn-dark" type="submit">Filter</button><a class="btn btn-light" href="{{ route('admin.dashboard') }}">Reset</a></form>
<div class="table-responsive"><table class="table admin-table align-middle mb-0"><thead><tr><th>Story</th><th>Category</th><th>Status</th><th>Published</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($articles as $article)<tr><td><div class="d-flex align-items-center gap-3">@if($article->image_url)<img class="admin-story-thumb" src="{{ $article->image_src }}" alt="">@else<div class="admin-story-thumb admin-thumb-empty"><i class="bi bi-image"></i></div>@endif<div><strong>{{ $article->title }}</strong><small>{{ $article->slug }}</small></div></div></td><td>{{ $article->category?->name }}</td><td><span class="admin-status {{ $article->published_at ? 'published' : 'draft' }}">{{ $article->published_at ? 'Published' : 'Draft' }}</span></td><td>{{ $article->published_at?->format('d M Y') ?? '—' }}</td><td class="text-end text-nowrap"><a class="btn btn-sm btn-light" href="{{ route('admin.articles.edit',$article) }}" title="Edit"><i class="bi bi-pencil"></i></a> @if($article->published_at)<a class="btn btn-sm btn-light" href="{{ route('articles.show',$article->slug) }}" target="_blank" title="View"><i class="bi bi-box-arrow-up-right"></i></a>@endif <form class="d-inline" method="POST" action="{{ route('admin.articles.destroy',$article) }}" data-confirm="Delete this story?">@csrf @method('DELETE')<button class="btn btn-sm btn-light text-danger" title="Delete"><i class="bi bi-trash"></i></button></form></td></tr>
@empty<tr><td colspan="5" class="text-center py-5 text-muted">No stories yet. Write your first one.</td></tr>@endforelse
</tbody></table></div><div class="admin-pagination">{{ $articles->links('pagination::bootstrap-5') }}</div></div>
@endsection
