@extends('layouts.admin')
@section('title','Site settings') @section('page','Site settings')
@section('content')
<div class="admin-page-heading"><div><span class="admin-kicker">SITE CONFIGURATION</span><h1>Settings</h1><p>Manage site identity, tracking and social links.</p></div></div>
<form method="POST" action="{{ route('admin.settings.update') }}">@csrf @method('PUT')
<div class="admin-panel p-4 mb-4"><div class="settings-section-title"><i class="bi bi-globe2"></i><div><h2>Site identity</h2><p>How the magazine is presented to readers.</p></div></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Site title</label><input class="form-control" name="site_title" value="{{ old('site_title',$settings['site_title'] ?? "Man's World Bangladesh") }}" required maxlength="120"></div><div class="col-md-6"><label class="form-label">Tagline</label><input class="form-control" name="tagline" value="{{ old('tagline',$settings['tagline'] ?? 'Stories with perspective.') }}" maxlength="240"></div></div></div>
<div class="admin-panel p-4 mb-4"><div class="settings-section-title"><i class="bi bi-graph-up-arrow"></i><div><h2>Analytics & advertising</h2><p>Enter IDs from your Google accounts. Tracking loads on public magazine pages.</p></div></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Google Analytics 4 Measurement ID</label><input class="form-control" name="ga_measurement_id" value="{{ old('ga_measurement_id',$settings['ga_measurement_id'] ?? '') }}" placeholder="G-XXXXXXXXXX"><div class="form-text">Find it in Google Analytics → Admin → Data streams.</div></div><div class="col-md-6"><label class="form-label">AdSense publisher ID</label><input class="form-control" name="adsense_publisher_id" value="{{ old('adsense_publisher_id',$settings['adsense_publisher_id'] ?? '') }}" placeholder="ca-pub-1234567890123456"><div class="form-text">Ad serving also requires an approved AdSense account and ad units.</div></div></div></div>
<div class="admin-panel p-4 mb-4"><div class="settings-section-title"><i class="bi bi-share"></i><div><h2>Social profiles</h2><p>Links used in the site footer.</p></div></div><div class="row g-3"><div class="col-md-4"><label class="form-label">Facebook URL</label><input class="form-control" name="facebook_url" value="{{ old('facebook_url',$settings['facebook_url'] ?? '') }}" placeholder="https://facebook.com/..."></div><div class="col-md-4"><label class="form-label">Instagram URL</label><input class="form-control" name="instagram_url" value="{{ old('instagram_url',$settings['instagram_url'] ?? '') }}" placeholder="https://instagram.com/..."></div><div class="col-md-4"><label class="form-label">YouTube URL</label><input class="form-control" name="youtube_url" value="{{ old('youtube_url',$settings['youtube_url'] ?? '') }}" placeholder="https://youtube.com/..."></div></div></div>
<button class="btn btn-danger btn-lg"><i class="bi bi-check2 me-2"></i>Save settings</button>
</form>
@endsection
